apiVersion: v2
appVersion: "0.25.0"
description: Zeebe Cluster Helm Chart for Kubernetes
name: zeebe-cluster-helm
type: application
version: 0.0.203
icon: https://zeebe.io/img/zeebe-logo.png
dependencies:
- name: elasticsearch
  repository: "https://helm.elastic.co"
  version: ~7.10.0
  condition: "elasticsearch.enabled"
- name: kibana
  repository: "https://helm.elastic.co" 
  version: ~7.10.0
  condition: "kibana.enabled"
- name: prometheus
  repository: "https://prometheus-community.github.io/helm-charts"
  version: ~12.0.1
  condition: "prometheus.enabled"
- name: jx3/jenkins-x-crds
  repository: "https://storage.googleapis.com/jenkinsxio/charts"
  version: 3.0.5