dependencies:
- name: elasticsearch
  repository: "https://helm.elastic.co"
  version: 7.5.1
  condition: "elasticsearch.enabled"
- name: kibana
  repository: "https://helm.elastic.co" 
  version: 7.5.1
  condition: "kibana.enabled"
- name: prometheus
  repository: "https://charts.helm.sh/stable"
  version: 8.5.11
  condition: "prometheus.enabled"